### ISSUE TITLE
When the variable is declared and assigned in the same statement, should it be considered unused?

### ISSUE THREAD

**Issue by sathyamurali** [Kami/node-unused#12]
Referring to the first test case with source code being 
var a = 5;

The variable a has been assigned a valid value.
Why is this being considered unused ?

Thanks a lot

**Comment by Kami** [comment]
Can you please provide more details and the actual code in question and the program output (I just want to make sure that I understand you correctly and that the variable is indeed not used somewhere else in the file)?

The thing is, this code reports about variables which are declared and not used later in the code. It doesn't matter if you declare a variable and assign it in the same line. If you don't use this variable somewhere else in the file / module, it will be reported as unused.

**Comment by sathyamurali** [comment]
Hi 
Thanks for prompt response.

 Sorry.  My interpretation of unused was wrong, now that I look at it.

I am looking for a solution for a use case which needs to find out variables declared but not assigned, which I guess is different.

Thanks so much..

**Comment by Kami** [comment]
No problem :)
